import {
  Info,
  Users,
  UserCheck,
  Globe,
  Mail,
  MapPin,
  Twitter,
  Send,
  Linkedin,
  Youtube,
  MessageSquare,
  Code,
  Search,
  HardDrive,
  Smartphone,
  Facebook,
  ShoppingCart,
  Tv,
} from "lucide-react";

export const Icons = {
  info: Info,
  users: Users,
  userCheck: UserCheck,
  globe: Globe,
  mail: Mail,
  mapPin: MapPin,
  twitter: Twitter,
  send: Send,
  linkedin: Linkedin,
  youtube: Youtube,
  messageSquare: MessageSquare,
  code: Code,
  search: Search,
  hardDrive: HardDrive,
  smartphone: Smartphone,
  facebook: Facebook,
  shoppingCart: ShoppingCart,
  tv: Tv,
};
